services:
    parsedown:
        class: Parsedown
    parsedown_extra:
        class: ParsedownExtra
    jeremyjumeau_parsedown.twig_extension:
        class: Jeremyjumeau\ParsedownBundle\Twig\ParsedownExtension
        arguments:
            - '@parsedown'
            - '@parsedown_extra'
        tags:
         - { name: twig.extension }
